class Product {
  static List<Product> getMovie() => [
        Product(
            "SamSung1",
            "Samsung Galaxy S9",
            "Samsung Galaxy S9 G9 0960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black",
            "50.99",
            "https://images-na.ssl-images-amazon.com/images/I/81%2Bh9mpyQmL._AC_SX679_.jpg",
            "Phones",
            "Samsung",
            65,
            false,
            false),
        Product(
            "Apple1",
            "Apple Watch Series 5",
            "Apple Watch Series 5 (GPS, 40mm) - Space Gray Aluminum Case with Black Sport Band",
            "100.99",
            "https://images-na.ssl-images-amazon.com/images/I/71DnIj%2B%2BjUL._AC_SX466_.jpg",
            "Watch",
            "Apple",
            12,
            false,
            false),
        Product(
            "LouisVutton1",
            "LOUIS VUITTON MONOGRAM LOCKIT PM",
            "Authentic Pre-Owned Louis Vuitton Monogram Lockit PM",
            "2.500",
            "https://cdn.shopify.com/s/files/1/0988/4598/products/louisvuittonmonogramlockit_4.jpg?v=1622276100",
            "Bag",
            "LouisVutton",
            22,
            false,
            false),
        Product(
            "SamSung1",
            "Samsung Galaxy S9",
            "Samsung Galaxy S9 G9 0960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black",
            "50.99",
            "https://images-na.ssl-images-amazon.com/images/I/81%2Bh9mpyQmL._AC_SX679_.jpg",
            "Phones",
            "Samsung",
            65,
            false,
            false),
        Product(
            "Apple1",
            "Apple Watch Series 5",
            "Apple Watch Series 5 (GPS, 40mm) - Space Gray Aluminum Case with Black Sport Band",
            "100.99",
            "https://images-na.ssl-images-amazon.com/images/I/71DnIj%2B%2BjUL._AC_SX466_.jpg",
            "Watch",
            "Apple",
            12,
            false,
            false),
        Product(
            "LouisVutton1",
            "LOUIS VUITTON MONOGRAM LOCKIT PM",
            "Authentic Pre-Owned Louis Vuitton Monogram Lockit PM",
            "2.500",
            "https://cdn.shopify.com/s/files/1/0988/4598/products/louisvuittonmonogramlockit_4.jpg?v=1622276100",
            "Bag",
            "LouisVutton",
            22,
            false,
            false),
        Product(
            "SamSung1",
            "Samsung Galaxy S9",
            "Samsung Galaxy S9 G9 0960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black",
            "50.99",
            "https://images-na.ssl-images-amazon.com/images/I/81%2Bh9mpyQmL._AC_SX679_.jpg",
            "Phones",
            "Samsung",
            65,
            false,
            false),
        Product(
            "Apple1",
            "Apple Watch Series 5",
            "Apple Watch Series 5 (GPS, 40mm) - Space Gray Aluminum Case with Black Sport Band",
            "100.99",
            "https://images-na.ssl-images-amazon.com/images/I/71DnIj%2B%2BjUL._AC_SX466_.jpg",
            "Watch",
            "Apple",
            12,
            false,
            false),
        Product(
            "LouisVutton1",
            "LOUIS VUITTON MONOGRAM LOCKIT PM",
            "Authentic Pre-Owned Louis Vuitton Monogram Lockit PM",
            "2.500",
            "https://cdn.shopify.com/s/files/1/0988/4598/products/louisvuittonmonogramlockit_4.jpg?v=1622276100",
            "Bag",
            "LouisVutton",
            22,
            false,
            false),
        Product(
            "SamSung1",
            "Samsung Galaxy S9",
            "Samsung Galaxy S9 G9 0960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black",
            "50.99",
            "https://images-na.ssl-images-amazon.com/images/I/81%2Bh9mpyQmL._AC_SX679_.jpg",
            "Phones",
            "Samsung",
            65,
            false,
            false),
        Product(
            "Apple1",
            "Apple Watch Series 5",
            "Apple Watch Series 5 (GPS, 40mm) - Space Gray Aluminum Case with Black Sport Band",
            "100.99",
            "https://images-na.ssl-images-amazon.com/images/I/71DnIj%2B%2BjUL._AC_SX466_.jpg",
            "Watch",
            "Apple",
            12,
            false,
            false),
        Product(
            "LouisVutton1",
            "LOUIS VUITTON MONOGRAM LOCKIT PM",
            "Authentic Pre-Owned Louis Vuitton Monogram Lockit PM",
            "2.500",
            "https://cdn.shopify.com/s/files/1/0988/4598/products/louisvuittonmonogramlockit_4.jpg?v=1622276100",
            "Bag",
            "LouisVutton",
            22,
            false,
            false),
      ];

  final String id;
  final String title;
  final String description;
  final String price;
  final String imgUrl;
  final String productCategoryName;
  final String brand;
  final int quantity;
  final bool isFavorite;
  final bool isPopular;

  Product(
      this.id,
      this.title,
      this.description,
      this.price,
      this.imgUrl,
      this.productCategoryName,
      this.brand,
      this.quantity,
      this.isFavorite,
      this.isPopular);
}
